version: '3'
services:
  slr-1:
    container_name: slr-1
    image: solr:9-slim
    ports:
      - "8983:8983"
    networks: [search]
    environment:
      ZK_HOST: "zoo-1:2181"
      SOLR_OPTS: "-Denable.packages=true"
    depends_on: [zoo-1]

  slr-2:
    container_name: slr-2
    image: solr:9-slim
    ports:
      - "8984:8984"
    networks: [search]
    environment:
      ZK_HOST: "zoo-2:2181"
      SOLR_OPTS: "-Denable.packages=true -Djetty.port=8984"
    depends_on: [zoo-2]

  slr-3:
    container_name: slr-3
    image: solr:9-slim
    ports:
      - "8985:8985"
    networks: [ search ]
    environment:
      ZK_HOST: "zoo-1:2181"
      SOLR_OPTS: "-Denable.packages=true -Djetty.port=8985"
    depends_on: [ zoo-1 ]

  slr-4:
    container_name: slr-4
    image: solr:9-slim
    ports:
      - "8986:8986"
    networks: [ search ]
    environment:
      ZK_HOST: "zoo-2:2181"
      SOLR_OPTS: "-Denable.packages=true -Djetty.port=8986"
    depends_on: [ zoo-2 ]

  zoo-1:
    container_name: zoo-1
    image: zookeeper:3.9
    networks: [search]
    ports:
      - "2181:2181"
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

  zoo-2:
    container_name: zoo-2
    image: zookeeper:3.9
    networks: [search]
    ports:
      - "2182:2181"
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

  zoon:
    image: elkozmon/zoonavigator:latest
    container_name: zoon
    networks: [search]
    ports:
      - "8080:9000"
    environment:
      HTTP_PORT: 9000
    restart: unless-stopped

networks:
  search:
    driver: bridge