solr:
  envs:
    - name: "dest"
      zkConnectionString: "localhost:2182"
    - name: "src"
      zkConnectionString: "localhost:2181"
spring:
  application:
    name: solrex-back
server:
  port: 8081
logging:
  level:
    root: info
springdoc:
  swagger-ui:
    use-root-path: true