spring:
  application:
    name: solrex-back
reindexer:
  dataimport-rh: /dih
  networking:
    nat: true
server:
  port: 8081
logging:
  level:
    root: info
springdoc:
  swagger-ui:
    use-root-path: true