solr:
  networking-mode: "legacy"
  envs:
    dest: "localhost:2182"
    src: "localhost:2181"
spring:
  application:
    name: solrex-back
server:
  port: 8081
logging:
  level:
    root: info
springdoc:
  default-property-example: false
  swagger-ui:
    use-root-path: true